apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev-johnpofo-monapp3-backend-cert
  namespace: dev-johnpofo-monapp3-backend
spec:
  secretName: dev-johnpofo-monapp3-backend-tls
  dnsNames:
    - dev.mydomain.api.flapi.org
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
