apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: staging-johnpofo-monapp3-backend-cert
  namespace: staging-johnpofo-monapp3-backend
spec:
  secretName: staging-johnpofo-monapp3-backend-tls
  dnsNames:
    - staging.mydomain.api.flapi.org
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
