apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod-johnpofo-monapp3-backend-cert
  namespace: prod-johnpofo-monapp3-backend
spec:
  secretName: prod-johnpofo-monapp3-backend-tls
  dnsNames:
    - mydomain.api.flapi.org
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
