apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-johnpofo-monapp3-backend-deployment
  namespace: prod-johnpofo-monapp3-backend
  labels:
    app: prod-johnpofo-monapp3-backend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: prod-johnpofo-monapp3-backend
  template:
    metadata:
      labels:
        app: prod-johnpofo-monapp3-backend
    spec:
      containers:
        - name: prod-johnpofo-monapp3-backend
          image: corentin35/johnpofo-monapp3-backend:${TAG_VERSION}
          imagePullPolicy: Always
          ports:
            - containerPort: 3333
          env:
            - name: PORT
              value: '3333'
          resources:
            requests:
              cpu: '300m'
              memory: '400Mi'
            limits:
              cpu: '600m'
              memory: '800Mi'
      imagePullSecrets:
        - name: regcred
