apiVersion: v1
kind: Service
metadata:
  name: prod-johnpofo-monapp3-backend-service
  namespace: prod-johnpofo-monapp3-backend
spec:
  ports:
    - port: 3333
      targetPort: 3333
  selector:
    app: prod-johnpofo-monapp3-backend
